name: pr check

on:
  pull_request:

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 19
        uses: actions/setup-node@v2
        with:
          node-version: 19
      - name: test
        run: |
          cd kanlang
          npm install
          npx nx test kanlang
  check-version-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: check diff
        run: |
          git diff --name-only -r HEAD^1 HEAD | grep package.json
  check-release-note-change:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: check diff
        run: |
          git diff --name-only -r HEAD^1 HEAD | grep releaseNotes

  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: "jq .version kanlang/package.json -r"
      - name: Show my version
        run: 'echo "version ${{ steps.version.outputs.value }}"'
